[package]
name = "chat"
version = "0.1.0"
authors = ["Blizik <portalblizik@gmail.com>"]
edition = "2018"

[dependencies]
mio = "0.6"
slab = "0.4"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
